### ISSUE TITLE
Shelly plug total energy wrong unit

### ISSUE THREAD

**Issue by elbandi** [UniverseDevel/zabbix-templates-shelly#2]
Shelly plug (and others) reports the total enery in Watt-minutes:
https://shelly-api-docs.shelly.cloud/gen1/#shelly-plug-plugs-meter-0

So meters-0.total displays wrong value: either change the unit to "Wm" (from Wh), or add a custom preprocess multipler (with 0.0166666666666666666666666666666 value).

**Comment by UniverseDevel** [comment]
You are correct, I will be fixing units in next upload.

**Comment by UniverseDevel** [comment]
I uploaded new templates, there is a change in how data are collected so might need to read instructions first. Problem in this issue should be fixed there.
